-- Create a table for contact messages
create table contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'New' check (status in ('New', 'Replied', 'Archived')),
  admin_reply text -- To store the advice given
);

-- Set up Row Level Security (RLS)
alter table contact_messages enable row level security;

-- Allow anyone to INSERT (send a message)
create policy "Anyone can send a message"
  on contact_messages for insert
  with check (true);

-- Allow Admins to SELECT, UPDATE, DELETE (simulated by checking if user is authenticated/admin)
-- Note: In a real prod app, you'd check for a specific role. 
-- For this simple setup, we'll allow authenticated users to read/update.
create policy "Authenticated users can view messages"
  on contact_messages for select
  using (auth.role() = 'authenticated');

create policy "Authenticated users can update messages"
  on contact_messages for update
  using (auth.role() = 'authenticated');
