
-- Create orders table
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT,
  address TEXT,
  city TEXT,
  province TEXT,
  postal_code TEXT,
  total_amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'Pending' -- Pending, Shipped, Delivered, Cancelled
);

-- Create order items table
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  product_name TEXT, -- Storing name snapshot in case product is deleted/changed
  quantity INTEGER NOT NULL,
  price NUMERIC NOT NULL
);

-- Enable RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Policies (Relaxed for testing/admin usage for now)
-- Allow public insert (for checkout) and select (for admin/user)
CREATE POLICY "Enable all access for orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for order_items" ON public.order_items FOR ALL USING (true) WITH CHECK (true);
