-- Create the products table
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  price NUMERIC NOT NULL, -- using numeric for money to avoid float errors
  category TEXT NOT NULL,
  image TEXT NOT NULL,
  description TEXT,
  rating NUMERIC DEFAULT 0
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access (everyone can see products)
CREATE POLICY "Enable read access for all users" 
ON public.products FOR SELECT 
USING (true);

-- Policy: Allow authenticated users (admins) to insert, update, delete
-- Note: In a real app, you might restrict this to specific user roles.
-- For now, any logged-in user (admin) can manage products.
CREATE POLICY "Enable all access for authenticated users" 
ON public.products FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
